server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aweb
    username: root
    password: rootroot

  security:
    user:
      name: user
      password: 123
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
