server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://rm-2zexpg78696o0ib7jeo.mysql.rds.aliyuncs.com:3306/aweb
    username: aweb
    password: aweb!@#123
  security:
    user:
      name: user
      password: 123
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
